"use client";

import { useState } from "react";
import { runResearch, ResearchResult } from "@/lib/api";
import ReportView from "@/components/ReportView";
import AskFollowUp from "@/components/AskFollowUp";
import Link from "next/link";

export default function Home() {
  const [ticker, setTicker] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<ResearchResult | null>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!ticker.trim()) return;

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const data = await runResearch(ticker.trim());
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white">
      {/* Header */}
      <div className="border-b border-slate-700 bg-slate-800/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <h1 className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">FinScout</h1>
          <Link href="/history" className="text-sm text-slate-300 hover:text-blue-400 transition">
            View history
          </Link>
        </div>
      </div>

      {/* Hero Section */}
      <div className="max-w-4xl mx-auto px-6 py-16">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold mb-4">AI-Powered Stock Research</h2>
          <p className="text-slate-400 text-lg max-w-2xl mx-auto">
            Get instant, AI-generated financial research reports. Powered by intelligent agents and verified fact-checking.
          </p>
        </div>

        {/* Search Form */}
        <div className="bg-slate-800 rounded-lg border border-slate-700 p-8 shadow-xl mb-8">
          <form onSubmit={handleSubmit} className="flex gap-3">
            <input
              type="text"
              value={ticker}
              onChange={(e) => setTicker(e.target.value.toUpperCase())}
              placeholder="Enter a ticker symbol (e.g., AAPL, GOOGL, MSFT)"
              className="flex-1 bg-slate-700 border border-slate-600 rounded-lg px-5 py-3 text-white placeholder-slate-400 focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 transition"
              maxLength={6}
              autoFocus
            />
            <button
              type="submit"
              disabled={loading}
              className="px-8 py-3 bg-gradient-to-r from-blue-500 to-cyan-500 text-white rounded-lg font-semibold hover:from-blue-600 hover:to-cyan-600 disabled:opacity-50 disabled:cursor-not-allowed transition transform hover:scale-105"
            >
              {loading ? (
                <span className="flex items-center gap-2">
                  <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 3v12m9-9a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  Researching...
                </span>
              ) : (
                "Research"
              )}
            </button>
          </form>

          {loading && (
            <div className="mt-4 p-4 bg-blue-900/30 border border-blue-500/30 rounded-lg">
              <p className="text-sm text-blue-200">
                ⚡ Fetching data, drafting, and fact-checking your report. This usually takes 10-20 seconds...
              </p>
            </div>
          )}

          {error && (
            <div className="mt-4 p-4 bg-red-900/30 border border-red-500/30 rounded-lg">
              <p className="text-sm text-red-200">❌ {error}</p>
            </div>
          )}
        </div>

        {/* Disclaimer */}
        <div className="bg-slate-800/50 border border-slate-700 rounded-lg p-4 text-center text-sm text-slate-400 mb-8">
          <p>⚠️ Generated by an AI agent from public data. Not financial advice. Verify independently before making investment decisions.</p>
        </div>
      </div>

      {result && (
        <div className="max-w-4xl mx-auto px-6 pb-16">
          <ReportView
            ticker={result.ticker}
            report={result.final_report}
            wasRevised={result.was_revised}
            fromCache={result.from_cache}
          />
          <AskFollowUp reportId={result.id} />
        </div>
      )}
    </main>
  );
}